### PR TITLE
Implement `odd?` for the `Integer`

### PR DESCRIPTION
**Pull request by mateusdeap**
This should tick one more box in #201. @TheGrizzlyDev I've decided to open this PR just so we don't pollute the issue thread. Like I said in discord, this is all quite new to me.

I'm also making this a draft just to make it clear this is not ready for reviewing and merging.

That being said, I did try to lookup how to make odd work for Bignums by looking at the MRI, but I don't think I'm actually implementing odd right even for a simple Fixnum

~Basing myself on the other methods, I added and IntegerValue argument to odd, in order to test wether it's a bignum, but I'm unsure if that's the correct thing to do.~

~I've not actually implemented an `odd` method for Bignum because I'm still trying to understand what a Bignum is and what does it mean to ask wether it is an odd number or not, in the context of computing: from the MRI it would seem that I need to take a specific digit (the left most, apparently) from the number and `&` it with 1 and that would mean it's odd. Is that really it?~

EDIT: I've since done some research and I believe I found what could be the right way to test wether a bignum is odd or not. What I do is take the bignum string, get the last char, convert it to an int and I mod that with 2 and test wether it is different from 0.

Not sure if this is right, but it seemed to be what MRI does and bignums seem to be the complement of a value, at least in the case of the fixnum specs.

The case for the bignum context I'll add in a comment below, as it's quite lengthy

### CODE REVIEW

**Comment by mateusdeap** [comment]
So, some specs still fail and, apparently, for odd reasons.

1. There are 2 specs that call `(-bignum_value(num))` on 0 and 1. What I find weird is that, in all my runs, BOTH end up calling the `is_odd` method in the `IntegerValue` class and the value of `m_integer` is 1 for both. I tried running this method in irb but I do not get the same result. I get, as one would expect, the value of calling `bignum(0)` but with a minus sign. However, if I puts the value of `(-bignum_value(0))` or `(-bignum_value(1))` I get 1, so there's something odd between running the method in irb and how it's run in the context of the spec...

2. Also, all of the specs in the `context "bignum"` block fail. Here, there are different huge numbers being generated, however, once execution goes through the cpp code, it never calls `is_odd` for `BignumValue` but only for `IntegerValue` and there, the value of `m_integer` is always `-9223372036854775808`, no matter what number it actually is. Maybe it's a limitation on the side of printf? I still don't know

**Comment by TheGrizzlyDev** [comment]
@mateusdeap yeah, the idea looks good to me :) Are the problems above still there? If so I can try having a look at it later

**Comment by mateusdeap** [comment]
@TheGrizzlyDev yes. I didn't have much time to figure them out since I posted my comment.

**Comment by seven1m** [comment]
@mateusdeap this is a good start. In order to get the `-bignum_value(num)` thing to work, we would need to implement `BignumValue::negate` as a virtual method too. Currently, when `-` (negate) is called, the Integer version is being called, and it doesn't properly handle the bignum.

It is a similar problem for the other tests, which use `num**power`. The `**` operator is bound to the `pow()` method on Integer, which has not yet been made Bignum-aware. For an example of what I mean by that, check out the `IntegerValue::add` method. You will see it properly promotes an overflowed result to a Bignum. The `pow` (`**`) method doesn't do that yet.

If I were you, I would probably comment out the failing tests, adding a note like `NATFIXME: need to work on IntegerValue::pow() so it promotes to Bignum`. Or something like that.

**Comment by mateusdeap** [comment]
I see. Will do.

**Comment by mateusdeap** [comment]
So, I've commented the specs that depend either on `IntegerValue::negate` or `IntegerValue::pow` and added comment explaining that once those are fixed, these should be revisited

**Comment by TheGrizzlyDev** [comment]
> So, @seven1m and @TheGrizzlyDev, I've commented the specs that depend either on `IntegerValue::negate` or `IntegerValue::pow` and added comments explaining that once those are fixed, these should be revisited

Looks great, but a bit in contrast with @seven1m instead of commenting out I usually prefer using xit to exclude the test so that it's marked as skipped.

**Comment by seven1m** [comment]
Yeah, I said "comment out" but I guess I meant skip. Sorry!

**Comment by mateusdeap** [comment]
Hm... true. Had forgotten that that was a possibility. And indeed, much better practice. I'll just fix it up real quick

**Comment by mateusdeap** [comment]
I asked this in the discord, but maybe you'll see it sooner here: Is there a way to mark a specific assertion as pending? I tried RSpec's `pending` and `skip`, but I get `NoMethodError`s. Any advice? Or should I just leave them commented?

**Comment by TheGrizzlyDev** [comment]
> I asked this in the discord, but maybe you'll see it sooner here: Is there a way to mark a specific assertion as pending? I tried RSpec's `pending` and `skip`, but I get `NoMethodError`s. Any advice? Or should I just leave them commented?

All the testing machinery is rewritten in Natalie (somewhere under the test folder) so you could just add that yourself, or for the sake of simplicity just using xit instead of it now and leaving the comments with NATFIXME, what do you think about it?

**Comment by seven1m** [comment]
It would be good to have _some_ specs for this yeah?

**Comment by mateusdeap** [comment]
@seven1m So, considering the conversation I had with @TheGrizzlyDev, we decided to mark them all pending while he added the methods to only mark specific assertions as pending in specs.

However, I could just revert the last commit and have the second `it` block marked as pending and the first one would run, but 2 of its assertions would be commented out.

**Comment by TheGrizzlyDev** [comment]
> @seven1m So, considering the conversation I had with @TheGrizzlyDev, we decided to mark them all pending while he added the methods to only mark specific assertions as pending in specs.
> 
> However, I could just revert the last commit and have the second `it` block marked as pending and the first one would run, but 2 of its assertions would be commented out.

I am honestly not a fan of a slightly divergent spec (other than just either skipping or completely commenting out) so I was thinking of a slightly different solution, can you add more tests (not the ones from ruby/spec) in the test package? Just covering the things you know to be working and have implemented? @seven1m how does this sound?

**Comment by mateusdeap** [comment]
Yeah, sure. No probs.

**Comment by seven1m** [comment]
Everyone, I'm sorry we killed the momentum on this. I went ahead and tweaked the specs so we can run a bit of _something_ and merged it. Thanks for your patience @mateusdeap, and please, keep up the work now that we ironed out some kinks in the process. :hugs:

**Comment by TheGrizzlyDev** [comment]
Very cool first PR @mateusdeap !

**Comment by mateusdeap** [comment]
Hey, no worries, and thanks a lot! As soon as I can I'll try and maybe tackle the methods that need fixing for the specs here to work!

**Pull request merged**
