### PR TITLE
Implement basic profiling using the Google Trace Event format

### PR DESCRIPTION
**Pull request by TheGrizzlyDev**
Spec: https://docs.google.com/document/d/1CvAClvFfyA5R-PhYUmn5OOQtYMH4h6I0nSsKchNAySU/preview#

This profiler is based on google's tracing format https://docs.google.com/document/d/1CvAClvFfyA5R-PhYUmn5OOQtYMH4h6I0nSsKchNAySU/preview# . It is an extremely simple format (at least the part we use) and since it is just a json it is somewhat easy to reason about. Personally my favourite UI for this is https://ui.perfetto.dev/ but you can also use chrome's embedded tracer instead.

Though we currently only expose this format, the API is made so it can be 'easily' extended to other formats as well.

### CODE REVIEW

**Comment by TheGrizzlyDev** [comment]
@seven1m my friend told me it is ready to be reviewed now :^)

**Comment by TheGrizzlyDev** [comment]
@seven1m your fix works, thanks a lot!

**Comment by seven1m** [comment]
@TheGrizzlyDev this is really cool! Do you have an idea what kind of overhead this adds when we are *not* profiling? I'm wondering if we need to conditionally compile these statements -- especially the ones around the GC allocation and collection -- since they could slow down normal operation.

If you can show me there is negligible difference, I'll :shipit:. :smile: Otherwise, I think we should make this an `#ifdef` kind of thing.

**Comment by TheGrizzlyDev** [comment]
> @TheGrizzlyDev this is really cool! Do you have an idea what kind of overhead this adds when we are _not_ profiling? I'm wondering if we need to conditionally compile these statements -- especially the ones around the GC allocation and collection -- since they could slow down normal operation.
> 
> If you can show me there is negligible difference, I'll :shipit:. smile Otherwise, I think we should make this an `#ifdef` kind of thing.

I think we can say with the last commit the impact of a disabled profiler is almost none :) 
image

Once I get some time this/next week I'll try making the profiler impact less the runtime it's profiling so we can get more accurate profiles :) For now though it is quite useful and highlights some issues on the GC side, especially during the marking phase.

**Comment by seven1m** [comment]
I haven't forgotten about this! I wanted to play around with it and just see how it affects traces before I merged. Very cool stuff, but I just ran out of time the last few days. :hugs:

**Comment by TheGrizzlyDev** [comment]
> I haven't forgotten about this! I wanted to play around with it and just see how it affects traces before I merged. Very cool stuff, but I just ran out of time the last few days. hugs

ahahahah no worries! It's a really good point, I've done that a bit as well and there are some interesting findings and things to fix (that would make a pretty cool youtube live/video by the way :D )

**Comment by seven1m** [comment]
I hate to be _that guy_ ... but this does add a teensy bit of overhead...

| script | master branch debug build | master branch release build | antonio's branch debug build | antonio's branch release build |
|---|---|---|---|---|
| examples/fib.rb | m_fib_dev | m_fib_rel | a_fib_dev | a_fib_rel |
| examples/boardslam.rb | m_bs_dev | m_bs_rel | a_bs_dev | a_bs_rel |

```
Benchmark 1: ./m_bs_rel 3 5 1
  Time (mean ± σ):     215.1 ms ±   6.3 ms    [User: 177.9 ms, System: 36.7 ms]
  Range (min … max):   204.7 ms … 228.8 ms    14 runs
 
Benchmark 2: ./a_bs_rel 3 5 1
  Time (mean ± σ):     224.1 ms ±  15.4 ms    [User: 187.6 ms, System: 36.3 ms]
  Range (min … max):   209.4 ms … 261.4 ms    12 runs
 
Summary
  './m_bs_rel 3 5 1' ran
    1.04 ± 0.08 times faster than './a_bs_rel 3 5 1'


tim@x230 ~/pp/natalie master 0 → hyperfine './m_fib_rel' './a_fib_rel'                                                                                                 3.0.3
Benchmark 1: ./m_fib_rel
  Time (mean ± σ):     230.4 ms ±  11.4 ms    [User: 196.8 ms, System: 33.4 ms]
  Range (min … max):   215.4 ms … 263.0 ms    13 runs
 
Benchmark 2: ./a_fib_rel
  Time (mean ± σ):     240.0 ms ±  22.6 ms    [User: 206.5 ms, System: 33.4 ms]
  Range (min … max):   220.7 ms … 309.4 ms    13 runs
 
  Warning: Statistical outliers were detected. Consider re-running this benchmark on a quiet PC without any interferences from other programs. It might help to use the '--warmup' or '--prepare' options.
 
Summary
  './m_fib_rel' ran
    1.04 ± 0.11 times faster than './a_fib_rel'


tim@x230 ~/pp/natalie master 0 → hyperfine './m_bs_dev 3 5 1' './a_bs_dev 3 5 1'                                                                                       3.0.3
Benchmark 1: ./m_bs_dev 3 5 1
  Time (mean ± σ):     647.2 ms ±   7.5 ms    [User: 603.4 ms, System: 43.0 ms]
  Range (min … max):   641.3 ms … 667.0 ms    10 runs
 
Benchmark 2: ./a_bs_dev 3 5 1
  Time (mean ± σ):     654.7 ms ±  27.6 ms    [User: 612.0 ms, System: 41.5 ms]
  Range (min … max):   622.1 ms … 702.3 ms    10 runs
 
Summary
  './m_bs_dev 3 5 1' ran
    1.01 ± 0.04 times faster than './a_bs_dev 3 5 1'


tim@x230 ~/pp/natalie master 0 → hyperfine './m_fib_dev' './a_fib_dev'                                                                                                 3.0.3
Benchmark 1: ./m_fib_dev
  Time (mean ± σ):     680.8 ms ±  12.2 ms    [User: 642.8 ms, System: 37.9 ms]
  Range (min … max):   663.5 ms … 703.4 ms    10 runs
 
Benchmark 2: ./a_fib_dev
  Time (mean ± σ):     726.2 ms ±  10.1 ms    [User: 689.4 ms, System: 36.5 ms]
  Range (min … max):   715.9 ms … 747.0 ms    10 runs
 
Summary
  './m_fib_dev' ran
    1.07 ± 0.02 times faster than './a_fib_dev'
```

...Now, I'm ok with merging as-is and we can circle back to make it better. But I don't think something that is optional should slow down normal operation.

What do you think about using some `#ifdef`s and enabling the feature with `rake build_release_profiled` or similar? Then we could compile out the instrumentation for regular builds... Thoughts?

**Comment by TheGrizzlyDev** [comment]
That feels a bit too much, are you sure you have compared with the commit from master this branched off from? Otherwise the difference may be caused by other changes. After work I'll try this again after rebasing on master, but ideally I want this feature to always be part of natalie and leave to our end users the ability of profiling or not and therefore I'd rather spend more time optimising this rather than disabling it in certain natalie builds :)

I'll let you know how this goes ;)

**Comment by seven1m** [comment]
You're right, I compared with _current_ master. I'll try again later...

**Comment by TheGrizzlyDev** [comment]
> You're right, I compared with _current_ master. I'll try again later...

ah no worries, I've tried as well but my machine seems to produce too many outliers, so I'll see how to create a more reliable test-bench. I really want this to be unnoticeable when not profiling and barely noticeable when profiling. This tool seems to be quite nice so hopefully it'll help me do that!

**Pull request merged**
