### PR TITLE
Make `Integer#pow` almost spec-compliant

### PR DESCRIPTION
**Pull request by ryangjchandler**
This takes it most of the way - just some BigInt fun-stuff to fix.

### CODE REVIEW

**Comment by ryangjchandler** [comment]
Minus the NATFIXME specs (related to rationals), this is now spec-compliant.

**Comment by seven1m** [comment]
Sorry @ryangjchandler, I chose to merge @richardboehme's PR first, so now this PR has some conflicts. :grimacing:

**Comment by ryangjchandler** [comment]
All good, will resolve later!

**Comment by ryangjchandler** [comment]
@seven1m All rebased and updated :)

**Pull request merged**
