### PR TITLE
Bind each module_function to static method

### PR DESCRIPTION
**Pull request by FnControlOption**

### CODE REVIEW

**Comment by seven1m** [comment]
@FnControlOption can you talk about your thinking here? Is this just to differentiate between methods that use `this` and those that don't?

**Comment by seven1m** [comment]
OK, I figured out what this is all about... It wasn't obvious to me why these needed to change, but looking in IRB tells the subtle story:

```
→ bin/natalie
nat> method(:abort)
#<Method: Kernel#abort(*)>
nat> Kernel.method(:abort)
#<Method: Kernel#abort(*)>
nat> 

→ irb
irb(main):001:0> method(:abort)
=> #<Method: Object(Kernel)#abort(*)>
irb(main):002:0> Kernel.method(:abort)
=> #<Method: Kernel.abort(*)>
irb(main):003:0> 
```

_Note: `Kernel.abort(*)` vs `Kernel#abort(*)`. Kinda wild.

**Comment by seven1m** [comment]
I'm sorry this will need to be rebased or have master merged in... :grimacing:

**Comment by FnControlOption** [comment]
> _Note: `Kernel.abort(*)` vs `Kernel#abort(*)`. Kinda wild._

Sorry, I should have explained that instead of opening this PR with another empty description 😅

**Pull request merged**
